#!/bin/sh
# postrm script for seaweedfs
# Script executed after the package is removed.

set -e

case "$1" in
  purge)
        rm -rf /var/lib/weed /var/log/weed
	# We do NOT remove the system user.
	;;
esac

#DEBHELPER#
